[package]
name = "wgpu-hang-test"
version = "0.1.0"
authors = ["bkell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.5"
zerocopy = "0.2.8"
log = "0.4.0"
env_logger = "0.7.1"
futures = "0.3"